### ISSUE TITLE
bug: flakiness in test  "SyncEngine › should not sync if messages were added within the sync threshold"

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub#215]
**What is the bug?**

A sync will trigger unnecessarily if the timestamp change happens to be from 9s -> 10s, so approximately 10% of the time. See details here: https://github.com/farcasterxyz/hub/pull/279#discussion_r1048644390, thanks to @adaddeo for investigating.

**How can it be reproduced? (optional)**

See above

**Additional context (optional)**

This bug causes two tests to fail sporadically locally and in CI 

```
Summary of all failing tests
FAIL src/network/sync/syncEngine.test.ts (12.641 s)
  ● SyncEngine › should not sync if messages were added within the sync threshold

    expect(received).toBeFalsy()

    Received: true

      118 |     // due to randomness
      119 |     const shouldSync = syncEngine.shouldSync(snapshot.excludedHashes, snapshot.numMessages + 1);
    > 120 |     expect(shouldSync).toBeFalsy();
          |                        ^
      121 |   });
      122 |
      123 |   test('initialize populates the trie with all existing messages', async () => {

      at Object.<anonymous> (src/network/sync/syncEngine.test.ts:120:24)
```

```
  ● differentialSync › sync converges even if signer removal is not within sync threshold

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 1668118779.897
    Received:    1668118780

      237 |
      238 |       const serverSnapshot = hubASyncEngine.snapshot;
    > 239 |       expect(hubASyncEngine.snapshotTimestamp).toBeLessThanOrEqual(now / 1000);
          |                                                ^
      240 |       expect(hubBSyncEngine.shouldSync(serverSnapshot.excludedHashes)).toBeTruthy();
      241 |
      242 |       await hubBSyncEngine.performSync(serverSnapshot.excludedHashes, hubARPCClient);

      at Object.<anonymous> (src/test/e2e/differentialSync.test.ts:239:48)

```

**Comment by varunsrin** [comment]
also see another similar failure for a different test here: https://github.com/farcasterxyz/hub/actions/runs/3397870041/jobs/5650406186

**Comment by sanjayprabhu** [comment]
Will investigate

**Comment by varunsrin** [comment]
adding more stack traces for flaky tests encountered locally

```
  ● differentialSync › sync converges even if signer removal is not within sync threshold

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 1668118779.897
    Received:    1668118780

      237 |
      238 |       const serverSnapshot = hubASyncEngine.snapshot;
    > 239 |       expect(hubASyncEngine.snapshotTimestamp).toBeLessThanOrEqual(now / 1000);
          |                                                ^
      240 |       expect(hubBSyncEngine.shouldSync(serverSnapshot.excludedHashes)).toBeTruthy();
      241 |
      242 |       await hubBSyncEngine.performSync(serverSnapshot.excludedHashes, hubARPCClient);

      at Object.<anonymous> (src/test/e2e/differentialSync.test.ts:239:48)
``` 


```
Summary of all failing tests
 FAIL  src/network/sync/syncEngine.test.ts (11.17 s)
  ● SyncEngine › should not sync if messages were added within the sync threshold

    expect(received).toBeFalsy()

    Received: true

      130 |     // Add a message after the snapshot, within the sync threshold
      131 |     await addMessagesWithTimestamps(user, [snapshotTimestamp + 3]);
    > 132 |     expect(syncEngine.shouldSync(snapshot.excludedHashes)).toBeFalsy();
          |                                                            ^
      133 |   });
      134 |
      135 |   test('initialize populates the trie with all existing messages', async () => {

      at Object.<anonymous> (src/network/sync/syncEngine.test.ts:132:60)
```


```
 FAIL  src/network/sync/syncEngine.test.ts (10.075 s)
  ● SyncEngine › should not sync if messages were added within the sync threshold

    expect(received).toBeFalsy()

    Received: true

      130 |     // Add a message after the snapshot, within the sync threshold
      131 |     await addMessagesWithTimestamps(user, [snapshotTimestamp + 3]);
    > 132 |     expect(syncEngine.shouldSync(snapshot.excludedHashes)).toBeFalsy();
          |                                                            ^
      133 |   });
      134 |
      135 |   test('initialize populates the trie with all existing messages', async () => {

      at Object.<anonymous> (src/network/sync/syncEngine.test.ts:132:60)
```


```


  ● SyncEngine › should not sync if messages were added within the sync threshold

    expect(received).toBeFalsy()

    Received: true

      130 |     // Add a message after the snapshot, within the sync threshold
      131 |     await addMessagesWithTimestamps(user, [snapshotTimestamp + 3]);
    > 132 |     expect(syncEngine.shouldSync(snapshot.excludedHashes)).toBeFalsy();
          |                                                            ^
      133 |   });
      134 |
      135 |   test('initialize populates the trie with all existing messages', async () => {

      at Object.<anonymous> (src/network/sync/syncEngine.test.ts:132:60)

```

**Comment by varunsrin** [comment]
@adaddeo if you want to take a stab at this, that would be tremendously appreciated

**Comment by adaddeo** [comment]
@adityapk00 should this one also be closed or is it still relevant?

**Comment by adityapk00** [comment]
Yup, I'll close this because Gossip now handles recent messages.
