### ISSUE TITLE
bug: contract subscriptions causing timeouts in hub e2e tests

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub#297]
**What is the bug?**

Jest does not exit correctly because some async operations are still running when the suite compeletes

```
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

**How can it be reproduced? (optional)**

Run `yarn test --runInBand --detectOpenHandles` locally to reproduce

**Additional context (optional)**

```
Jest has detected the following 5 open handles potentially keeping Jest from exiting:

  ●  Timeout

      71 |
      72 |     // Setup IdRegistry contract
    > 73 |     this._idRegistryContract.on('Register', (to: string, id: BigNumber, _recovery, _url, event: Event) => {
         |                              ^
      74 |       this.cacheIdRegistryEvent('', to, id, IdRegistryEventType.IdRegistryRegister, event);
      75 |     });
      76 |     this._idRegistryContract.on('Transfer', (from: string, to: string, id: BigNumber, event: Event) => {

      at JsonRpcProvider.set (node_modules/@ethersproject/providers/src.ts/base-provider.ts:1213:28)
      at JsonRpcProvider.Object.<anonymous>.BaseProvider._startEvent (node_modules/@ethersproject/providers/src.ts/base-provider.ts:2103:21)
      at JsonRpcProvider.Object.<anonymous>.JsonRpcProvider._startEvent (node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:648:26)
      at JsonRpcProvider.Object.<anonymous>.BaseProvider._addEventListener (node_modules/@ethersproject/providers/src.ts/base-provider.ts:2113:14)
      at JsonRpcProvider.Object.<anonymous>.BaseProvider.on (node_modules/@ethersproject/providers/src.ts/base-provider.ts:2119:21)
      at Contract.Object.<anonymous>.BaseContract._addEventListener (node_modules/@ethersproject/contracts/src.ts/index.ts:1034:31)
      at Contract.Object.<anonymous>.BaseContract.on (node_modules/@ethersproject/contracts/src.ts/index.ts:1059:14)
      at new EthEventsProvider (src/storage/engine/flatbuffers/providers/ethEventsProvider.ts:73:30)
      at Function.makeWithGoerli (src/storage/engine/flatbuffers/providers/ethEventsProvider.ts:115:22)
      at new Hub (src/hub.ts:117:50)
      at Object.<anonymous> (src/test/e2e/hub.test.ts:49:11)
```

**Comment by varunsrin** [comment]
some open listeners were cleaned up, however this issue seems to persist: https://github.com/farcasterxyz/hub/pull/299
